fix: [2.5] remove stray nullptr arg to ComputeUserAgentString
aws-sdk-cpp 1.9.234 on 2.5 declares Aws::Client::ComputeUserAgentString()
with zero args (matching the local forward declaration in this file).
Passing nullptr breaks compilation with:
  error: too many arguments to function
    'Aws::String Aws::Client::ComputeUserAgentString()'

Signed-off-by: xianliang.li <xianliang.li@zilliz.com>